// This file is automatically generated by `Build.ps1 generate-scripts`.

import jetbrains.buildServer.configs.kotlin.*
import jetbrains.buildServer.configs.kotlin.buildFeatures.*
import jetbrains.buildServer.configs.kotlin.buildSteps.powerShell
import jetbrains.buildServer.configs.kotlin.buildSteps.PowerShellStep
import jetbrains.buildServer.configs.kotlin.failureConditions.*
import jetbrains.buildServer.configs.kotlin.triggers.*
import jetbrains.buildServer.configs.kotlin.projectFeatures.*

version = "2025.11"

project {

    buildType(PublicUpdateSearch)

    buildTypesOrder = arrayListOf(PublicUpdateSearch)

}

object PublicUpdateSearch : BuildType({

    name = "Deploy [Public]"

    type = Type.DEPLOYMENT

    params {
        text(
            "UpdateSearch.Arguments", 
            "", 
            label ="Build.ps1 Arguments",
            description = "Arguments to append to the 'Update search' build step.", allowEmpty = true)
        param("UpdateSearch.Timeout", "30")
    }

    vcs {
        root(AbsoluteId("WebsitesAndBusinessSystems_MetalamaMarketplace"))
     checkoutMode = CheckoutMode.ON_AGENT
    }

    steps {
        powerShell {
            name = "Update search"
            id = "UpdateSearch"
            edition = PowerShellStep.Edition.Core
            scriptMode = file {
                path = "Build.ps1"
            }
            noProfile = false
            scriptArgs = "search update --timeout %UpdateSearch.Timeout% %UpdateSearch.Arguments%"
        }
    }

    requirements {
        matches("teamcity.agent.jvm.os.family", "Windows")
        matches("teamcity.agent.jvm.os.arch", "amd64")
        equals("env.BuildAgentType", "docker-win-x64-md")
    }

    features {
        swabra {
            filesCleanup = Swabra.FilesCleanup.BEFORE_BUILD
            lockingProcesses = Swabra.LockingProcessPolicy.KILL
            verbose = true
        }
    }

    triggers {
        schedule {
            schedulingPolicy = daily {
                hour = 0
                minute = 0
            }
            branchFilter = "+:master"
            triggerBuild = always()
            withPendingChangesOnly = false
        }
    }

})

